#posts account data
curl -H "Content-Type: application/json" -X POST -d '{"balance": 100, "name":"checking"}'  "http://localhost:3000/accounts" 

#gets account data
curl "http://localhost:3000/accounts" 

#updates account data at specific id
#NOTE: replace 'id' in "http://localhost:3000/accounts/id" with the id generated by the previous POST command
curl -H 'Content-Type: application/json' -X PUT -d '{"balance": 200, "name": "savings"}'  "http://localhost:3000/accounts/id"

#deletes account data at specific id
#NOTE: replace 'id' in "http://localhost:3000/accounts/id" with the id generated by the previous POST command
curl -X DELETE "http://localhost:3000/accounts/id" 

#POSTMAN LINK LIBRARY
https://www.getpostman.com/collections/4b0f687d3f0a1e47c025
